// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotinoAppka.Data;

#nullable disable

namespace NotinoAppka.Migrations
{
    [DbContext(typeof(APIcontext))]
    partial class APIcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotinoAppka.Models.DataFiles", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"));

                    b.Property<int?>("NotinoModelId")
                        .HasColumnType("int");

                    b.Property<string>("optional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("some")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataId");

                    b.HasIndex("NotinoModelId");

                    b.ToTable("DataFiles");
                });

            modelBuilder.Entity("NotinoAppka.Models.NotinoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotinoData");
                });

            modelBuilder.Entity("NotinoAppka.Models.DataFiles", b =>
                {
                    b.HasOne("NotinoAppka.Models.NotinoModel", null)
                        .WithMany("Data")
                        .HasForeignKey("NotinoModelId");
                });

            modelBuilder.Entity("NotinoAppka.Models.NotinoModel", b =>
                {
                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
